version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    stop_grace_period: 1s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
        
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

    restart: always
    stop_grace_period: 1s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"


  keepalived:
    build:
      context: ./keepalived
      dockerfile: Dockerfile
    volumes:
      # Master
      - ./keepalived/keepalived-master.conf:/etc/keepalived/keepalived.conf 
      # Backup
      # - ./keepalived/keepalived-backup.conf:/etc/keepalived/keepalived.conf
    network_mode: "host"
    privileged: true
    restart: always
    depends_on:
      - web
    stop_grace_period: 1s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
